# Site settings
title: AJL Nettoyage Peinture
email: yann.tho.le.moigne@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: ""
url: "" # the base hostname & protocol for your site

facebook_username: Ajl-peinture-nettoyage
facebook_url: https://www.facebook.com/Ajl-peinture-nettoyage-114156446955183/

# Build settings
markdown: kramdown
